use_frameworks!

platform :ios, '9.0'

target 'JDFlutter_Example' do
  pod 'JDFlutter', :path => '../'

  target 'JDFlutter_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
